import {
  ArrowUpRight,
  Calendar,
  ChevronLeft,
  ChevronUp,
  Clock,
  Contact,
  ExternalLink,
  Eye,
  Home,
  Link,
  Menu,
  PenLine,
  Send,
} from "lucide-react";
import {
  FiGithub,
  FiInstagram,
  FiLinkedin,
  FiMail,
  FiTwitter,
} from "react-icons/fi";

export const Icons = {
  github: FiGithub,
  linkedin: FiLinkedin,
  twitter: FiTwitter,
  instagram: FiInstagram,
  mail: FiMail,
  externalLink: ExternalLink,
  link: Link,
  arrowUpRight: ArrowUpRight,
  arrowBack: ChevronLeft,
  arrowUp: ChevronUp,
  calender: Calendar,
  clock: Clock,
  eye: Eye,
  send: Send,
  menu: Menu,
  home: Home,
  contact: Contact,
  blog: PenLine,
};
